name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        conda install -c bioconda samtools
        if [ -f requirements.txt ]; then
            pip install -r requirements.txt
        fi
    - name: Install CNVisualize
      run: |
        python -m pip install --upgrade build
        python -m build
        cd dist/
        pip install CNVisualize_project-0.1.0.tar.gz
    - name: Test with pytest
      run: |
        pytest .